#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: GET
healthcheck:
    path: /healthcheck
    controller: App\Controller\SystemController::healthcheck
    methods: GET
store_citizen:
    path: /citizen
    controller: App\Controller\CitizenController::store
    methods: POST
store_lawyer:
    path: /lawyer
    controller: App\Controller\LawyerController::store
    methods: POST
login_auth:
    path: /login
    controller: App\Controller\AuthController::login
    methods: POST
store_appointment:
    path: /appointment
    controller: App\Controller\AppointmentController::store
    methods: POST

list_citizen:
    path: /citizen
    controller: App\Controller\CitizenController::list
    methods: GET
list_lawyer:
    path: /lawyer
    controller: App\Controller\LawyerController::list
    methods: GET

