#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\DefaultController::index
    methods: GET
healthcheck:
    path: /healthcheck
    controller: App\Controller\SystemController::healthcheck
    methods: GET
login_auth:
    path: /login
    controller: App\Controller\AuthController::login
    methods: POST
store_citizen:
    path: /citizen
    controller: App\Controller\CitizenController::store
    methods: POST
list_citizen:
    path: /citizen/{page}
    controller: App\Controller\CitizenController::list
    defaults:
        page: 1
    requirements:
        page: '\d+'
    methods: GET
store_lawyer:
    path: /lawyer
    controller: App\Controller\LawyerController::store
    methods: POST
list_lawyer:
    path: /lawyer/{page}
    controller: App\Controller\LawyerController::list
    defaults:
        page: 1
    requirements:
        page: '\d+'
    methods: GET
store_appointment:
    path: /appointment
    controller: App\Controller\AppointmentController::store
    methods: POST
list_appointment:
    path: /appointment/{page}
    controller: App\Controller\AppointmentController::list
    defaults:
        page: 1
    requirements:
        page: '\d+'
    methods: GET
delete_appointment:
    path: /appointment
    controller: App\Controller\AppointmentController::remove
    methods: DELETE
update_status_appointment:
    path: /appointment
    controller: App\Controller\AppointmentController::updateStatus
    methods: PATCH
update_appointment:
    path: /appointment
    controller: App\Controller\AppointmentController::update
    methods: PUT

